apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deen-todo-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/MMuyideen/aws-week4-kubemanifest.git
    targetRevision: HEAD
    path: kube_manifest/
  destination: 
    server: https://kubernetes.default.svc
    namespace: deen-todo
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true