apiVersion: apps/v1
kind: Deployment
metadata:
  name: deen-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deen-todo
  template:
    metadata:
      labels:
        app: deen-todo
    spec:
      containers:
      - name: deen-todo
        image: fullbloodprince/deen-todo:build-60
        ports:
        - containerPort: 8000
